package: cookie_consent
version: '2.1.0-beta1'
author: Friends Of REDAXO
supportpage: https://github.com/FriendsOfREDAXO/cookie_consent

# Seiten
page:
    title: 'Cookie Consent'
    icon: rex-icon fa-empire
    perm: cookie_consent[]
    subpages:
        configuration:
            title: 'translate:configuration'
            icon: rex-icon fa-cogs
        global_configuration:
            title: 'translate:global_configuration'
            icon: rex-icon fa-cog
        configuration_test:
            title: 'translate:configuration_test'
            icon: rex-icon fa-eercast
        help:
            title: 'translate:help'
            icon: rex-icon fa-wrench
            subpages:
              readme:
                title: 'translate:help'
              templates:
                title: 'translate:templates'


requires:
    redaxo: '^5.1'
